services:
  selenium:
    image: selenium/standalone-firefox
    ports:
      - 4444:4444
    healthcheck:
      test: "curl --fail http://localhost:4444  || exit 1"
      interval: 10s
      timeout: 5s
      retries: 3
  web:
    build: .
    volumes:
      - ./image:/app/image 
    depends_on:
      selenium:
        condition: service_healthy